#!/bin/bash

# Get the directory where this app bundle is located
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../" && pwd)"

# Open Terminal and run the startup script
osascript -e "
tell application \"Terminal\"
    activate
    do script \"cd '$APP_DIR' && ./start-energytracker.sh\"
end tell
"
